version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: nuxt_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: usrcms
      POSTGRES_PASSWORD: Utorak30Sep
      POSTGRES_DB: nuxt_pg_cms_db
    ports:
      - "5432:5432" # 👈 host=5432, container=5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./.docker/postgres/init:/docker-entrypoint-initdb.d

  mysql:
    image: mysql:8.3
    container_name: nuxt_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Freitag%230605
      MYSQL_DATABASE: sta3wp
      MYSQL_USER: rooth3wp
      MYSQL_PASSWORD: Freitag%230605
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./.docker/mysql/init:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql

  redis:
    image: redis:7
    container_name: nuxt_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
      - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

  mongodb:
    image: mongo:7
    container_name: nuxt_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
      - ./.docker/mongodb/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: yourpassword

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8082:8080"

# DuckDB nije service – mountaš lokalni fajl iz .docker/duckdb/
volumes:
  postgres_data:
  mysql_data:
  redis_data:
  mongo_data:
