packages:
  - app/*
  - server
  - packages/shared
  - server/prisma
catalogs:
  prisma:
    prisma: latest

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - esbuild
  - prisma
  - sharp
  - vue-demi
