/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, '__esModule', { value: true })

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  objectEnumValues,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam
} = require('./runtime/wasm-engine-edge.js')

const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: '6.17.1',
  engine: '272a37d34178c2894197e17273bf937f25acdeac'
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
 * Extensions
 */
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}

/**
 * Enums
 */
exports.Prisma.MgArticleScalarFieldEnum = {
  id: 'id',
  title: 'title',
  body: 'body',
  tags: 'tags',
  created: 'created'
}

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
}

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
}

exports.Prisma.ModelName = {
  mgArticle: 'mgArticle'
}
/**
 * Create the Client
 */
const config = {
  generator: {
    name: 'mongo',
    provider: {
      fromEnvVar: null,
      value: 'prisma-client-js'
    },
    output: {
      value:
        '/mnt/b8570372-045b-4bb5-af27-fff9180761c0/projekte/nuxt-wp-multilang-theme/server/prisma/generated/mongo',
      fromEnvVar: null
    },
    config: {
      engineType: 'library'
    },
    binaryTargets: [
      {
        fromEnvVar: null,
        value: 'debian-openssl-3.0.x',
        native: true
      }
    ],
    previewFeatures: [],
    sourceFilePath:
      '/mnt/b8570372-045b-4bb5-af27-fff9180761c0/projekte/nuxt-wp-multilang-theme/server/prisma/adapters/schema-mongo.prisma',
    isCustomOutput: true
  },
  relativeEnvPaths: {
    rootEnvPath: '../../../../.env',
    schemaEnvPath: '../../../../.env'
  },
  relativePath: '../../adapters',
  clientVersion: '6.17.1',
  engineVersion: '272a37d34178c2894197e17273bf937f25acdeac',
  datasourceNames: ['mongo'],
  activeProvider: 'mongodb',
  postinstall: false,
  inlineDatasources: {
    mongo: {
      url: {
        fromEnvVar: 'MONGO_URL',
        value: null
      }
    }
  },
  inlineSchema:
    '//prisma/adapters/schema-mongo.prisma\ngenerator mongo {\n  provider = "prisma-client-js"\n  //previewFeatures = ["postgresqlExtensions"]\n  //output   = "../../node_modules/.prisma/mongo"\n  output   = "../generated/mongo"\n}\n\ndatasource mongo {\n  provider = "mongodb"\n  url      = env("MONGO_URL")\n}\n\nmodel mgArticle {\n  id      String   @id @default(auto()) @map("_id") @mongo.ObjectId\n  title   String\n  body    String?\n  tags    String[]\n  created DateTime @default(now())\n}\n\n// npx prisma generate --schema=prisma/schema-postgres.prisma\n// npx prisma generate --schema=prisma/schema-mysql.prisma\n// npx prisma generate --schema=prisma/schema-mongo.prisma\n',
  inlineSchemaHash: '7e48be2d038b71112c751d9c7382f23ae8f5487b7733312b67d6dd1781fc229d',
  copyEngine: true
}
config.dirname = '/'

config.runtimeDataModel = JSON.parse(
  '{"models":{"mgArticle":{"fields":[{"name":"id","kind":"scalar","type":"String","dbName":"_id"},{"name":"title","kind":"scalar","type":"String"},{"name":"body","kind":"scalar","type":"String"},{"name":"tags","kind":"scalar","type":"String"},{"name":"created","kind":"scalar","type":"DateTime"}],"dbName":null}},"enums":{},"types":{}}'
)
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.engineWasm = {
  getRuntime: async () => require('./query_engine_bg.js'),
  getQueryEngineWasmModule: async () => {
    const loader = (await import('#wasm-engine-loader')).default
    const engine = (await loader).default
    return engine
  }
}
config.compilerWasm = undefined

config.injectableEdgeEnv = () => ({
  parsed: {
    MONGO_URL:
      (typeof globalThis !== 'undefined' && globalThis['MONGO_URL']) ||
      (typeof process !== 'undefined' && process.env && process.env.MONGO_URL) ||
      undefined
  }
})

if (
  (typeof globalThis !== 'undefined' && globalThis['DEBUG']) ||
  (typeof process !== 'undefined' && process.env && process.env.DEBUG) ||
  undefined
) {
  Debug.enable(
    (typeof globalThis !== 'undefined' && globalThis['DEBUG']) ||
      (typeof process !== 'undefined' && process.env && process.env.DEBUG) ||
      undefined
  )
}

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
