/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, '__esModule', { value: true })

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')

const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: '6.17.1',
  engine: '272a37d34178c2894197e17273bf937f25acdeac'
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.validator = Public.validator

/**
 * Extensions
 */
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}

/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
})

exports.Prisma.As_actionscheduler_actionsScalarFieldEnum = {
  action_id: 'action_id',
  hook: 'hook',
  status: 'status',
  scheduled_date_gmt: 'scheduled_date_gmt',
  scheduled_date_local: 'scheduled_date_local',
  args: 'args',
  schedule: 'schedule',
  group_id: 'group_id',
  attempts: 'attempts',
  last_attempt_gmt: 'last_attempt_gmt',
  last_attempt_local: 'last_attempt_local',
  claim_id: 'claim_id',
  extended_args: 'extended_args',
  priority: 'priority'
}

exports.Prisma.As_actionscheduler_claimsScalarFieldEnum = {
  claim_id: 'claim_id',
  date_created_gmt: 'date_created_gmt'
}

exports.Prisma.As_actionscheduler_groupsScalarFieldEnum = {
  group_id: 'group_id',
  slug: 'slug'
}

exports.Prisma.As_actionscheduler_logsScalarFieldEnum = {
  log_id: 'log_id',
  action_id: 'action_id',
  message: 'message',
  log_date_gmt: 'log_date_gmt',
  log_date_local: 'log_date_local'
}

exports.Prisma.As_awb_critical_cssScalarFieldEnum = {
  id: 'id',
  css_key: 'css_key',
  mobile_css: 'mobile_css',
  desktop_css: 'desktop_css',
  mobile_preloads: 'mobile_preloads',
  desktop_preloads: 'desktop_preloads',
  updated_at: 'updated_at'
}

exports.Prisma.As_cli_cookie_scanScalarFieldEnum = {
  id_cli_cookie_scan: 'id_cli_cookie_scan',
  status: 'status',
  created_at: 'created_at',
  total_url: 'total_url',
  total_cookies: 'total_cookies',
  current_action: 'current_action',
  current_offset: 'current_offset'
}

exports.Prisma.As_cli_cookie_scan_categoriesScalarFieldEnum = {
  id_cli_cookie_category: 'id_cli_cookie_category',
  cli_cookie_category_name: 'cli_cookie_category_name',
  cli_cookie_category_description: 'cli_cookie_category_description'
}

exports.Prisma.As_cli_cookie_scan_cookiesScalarFieldEnum = {
  id_cli_cookie_scan_cookies: 'id_cli_cookie_scan_cookies',
  id_cli_cookie_scan: 'id_cli_cookie_scan',
  id_cli_cookie_scan_url: 'id_cli_cookie_scan_url',
  cookie_id: 'cookie_id',
  expiry: 'expiry',
  type: 'type',
  category: 'category',
  category_id: 'category_id',
  description: 'description'
}

exports.Prisma.As_cli_cookie_scan_urlScalarFieldEnum = {
  id_cli_cookie_scan_url: 'id_cli_cookie_scan_url',
  id_cli_cookie_scan: 'id_cli_cookie_scan',
  url: 'url',
  scanned: 'scanned',
  total_cookies: 'total_cookies'
}

exports.Prisma.As_cli_scriptsScalarFieldEnum = {
  id: 'id',
  cliscript_title: 'cliscript_title',
  cliscript_category: 'cliscript_category',
  cliscript_type: 'cliscript_type',
  cliscript_status: 'cliscript_status',
  cliscript_description: 'cliscript_description',
  cliscript_key: 'cliscript_key',
  type: 'type'
}

exports.Prisma.As_commentmetaScalarFieldEnum = {
  meta_id: 'meta_id',
  comment_id: 'comment_id',
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.As_commentsScalarFieldEnum = {
  comment_ID: 'comment_ID',
  comment_post_ID: 'comment_post_ID',
  comment_author: 'comment_author',
  comment_author_email: 'comment_author_email',
  comment_author_url: 'comment_author_url',
  comment_author_IP: 'comment_author_IP',
  comment_date: 'comment_date',
  comment_date_gmt: 'comment_date_gmt',
  comment_content: 'comment_content',
  comment_karma: 'comment_karma',
  comment_approved: 'comment_approved',
  comment_agent: 'comment_agent',
  comment_type: 'comment_type',
  comment_parent: 'comment_parent',
  user_id: 'user_id'
}

exports.Prisma.As_fusion_form_entriesScalarFieldEnum = {
  id: 'id',
  submission_id: 'submission_id',
  form_id: 'form_id',
  field_id: 'field_id',
  value: 'value',
  privacy: 'privacy',
  data: 'data'
}

exports.Prisma.As_fusion_form_fieldsScalarFieldEnum = {
  id: 'id',
  form_id: 'form_id',
  field_name: 'field_name',
  field_label: 'field_label',
  data: 'data'
}

exports.Prisma.As_fusion_form_submissionsScalarFieldEnum = {
  id: 'id',
  form_id: 'form_id',
  time: 'time',
  source_url: 'source_url',
  post_id: 'post_id',
  user_id: 'user_id',
  user_agent: 'user_agent',
  ip: 'ip',
  is_read: 'is_read',
  privacy_scrub_date: 'privacy_scrub_date',
  on_privacy_scrub: 'on_privacy_scrub',
  data: 'data'
}

exports.Prisma.As_fusion_formsScalarFieldEnum = {
  id: 'id',
  form_id: 'form_id',
  views: 'views',
  submissions_count: 'submissions_count',
  data: 'data'
}

exports.Prisma.As_layersliderScalarFieldEnum = {
  id: 'id',
  group_id: 'group_id',
  author: 'author',
  name: 'name',
  slug: 'slug',
  data: 'data',
  date_c: 'date_c',
  date_m: 'date_m',
  schedule_start: 'schedule_start',
  schedule_end: 'schedule_end',
  flag_hidden: 'flag_hidden',
  flag_deleted: 'flag_deleted',
  flag_popup: 'flag_popup',
  flag_group: 'flag_group'
}

exports.Prisma.As_layerslider_revisionsScalarFieldEnum = {
  id: 'id',
  slider_id: 'slider_id',
  author: 'author',
  data: 'data',
  date_c: 'date_c'
}

exports.Prisma.As_linksScalarFieldEnum = {
  link_id: 'link_id',
  link_url: 'link_url',
  link_name: 'link_name',
  link_image: 'link_image',
  link_target: 'link_target',
  link_description: 'link_description',
  link_visible: 'link_visible',
  link_owner: 'link_owner',
  link_rating: 'link_rating',
  link_updated: 'link_updated',
  link_rel: 'link_rel',
  link_notes: 'link_notes',
  link_rss: 'link_rss'
}

exports.Prisma.As_loginizer_logsScalarFieldEnum = {
  username: 'username',
  time: 'time',
  count: 'count',
  lockout: 'lockout',
  ip: 'ip',
  url: 'url'
}

exports.Prisma.As_optionsScalarFieldEnum = {
  option_id: 'option_id',
  option_name: 'option_name',
  option_value: 'option_value',
  autoload: 'autoload'
}

exports.Prisma.As_postmetaScalarFieldEnum = {
  meta_id: 'meta_id',
  post_id: 'post_id',
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.As_postsScalarFieldEnum = {
  ID: 'ID',
  post_author: 'post_author',
  post_date: 'post_date',
  post_date_gmt: 'post_date_gmt',
  post_content: 'post_content',
  post_title: 'post_title',
  post_excerpt: 'post_excerpt',
  post_status: 'post_status',
  comment_status: 'comment_status',
  ping_status: 'ping_status',
  post_password: 'post_password',
  post_name: 'post_name',
  to_ping: 'to_ping',
  pinged: 'pinged',
  post_modified: 'post_modified',
  post_modified_gmt: 'post_modified_gmt',
  post_content_filtered: 'post_content_filtered',
  post_parent: 'post_parent',
  guid: 'guid',
  menu_order: 'menu_order',
  post_type: 'post_type',
  post_mime_type: 'post_mime_type',
  comment_count: 'comment_count'
}

exports.Prisma.As_term_relationshipsScalarFieldEnum = {
  object_id: 'object_id',
  term_taxonomy_id: 'term_taxonomy_id',
  term_order: 'term_order'
}

exports.Prisma.As_term_taxonomyScalarFieldEnum = {
  term_taxonomy_id: 'term_taxonomy_id',
  term_id: 'term_id',
  taxonomy: 'taxonomy',
  description: 'description',
  parent: 'parent',
  count: 'count'
}

exports.Prisma.As_termmetaScalarFieldEnum = {
  meta_id: 'meta_id',
  term_id: 'term_id',
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.As_termsScalarFieldEnum = {
  term_id: 'term_id',
  name: 'name',
  slug: 'slug',
  term_group: 'term_group'
}

exports.Prisma.As_tm_taskmetaScalarFieldEnum = {
  meta_id: 'meta_id',
  task_id: 'task_id',
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.As_tm_tasksScalarFieldEnum = {
  id: 'id',
  user_id: 'user_id',
  type: 'type',
  class_identifier: 'class_identifier',
  attempts: 'attempts',
  description: 'description',
  time_created: 'time_created',
  last_locked_at: 'last_locked_at',
  status: 'status'
}

exports.Prisma.As_usermetaScalarFieldEnum = {
  umeta_id: 'umeta_id',
  user_id: 'user_id',
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.As_usersScalarFieldEnum = {
  ID: 'ID',
  user_login: 'user_login',
  user_pass: 'user_pass',
  user_nicename: 'user_nicename',
  user_email: 'user_email',
  user_url: 'user_url',
  user_registered: 'user_registered',
  user_activation_key: 'user_activation_key',
  user_status: 'user_status',
  display_name: 'display_name'
}

exports.Prisma.As_wpo_404_detectorScalarFieldEnum = {
  ID: 'ID',
  url: 'url',
  request_timestamp: 'request_timestamp',
  request_count: 'request_count',
  referrer: 'referrer'
}

exports.Prisma.As_yoast_indexableScalarFieldEnum = {
  id: 'id',
  permalink: 'permalink',
  permalink_hash: 'permalink_hash',
  object_id: 'object_id',
  object_type: 'object_type',
  object_sub_type: 'object_sub_type',
  author_id: 'author_id',
  post_parent: 'post_parent',
  title: 'title',
  description: 'description',
  breadcrumb_title: 'breadcrumb_title',
  post_status: 'post_status',
  is_public: 'is_public',
  is_protected: 'is_protected',
  has_public_posts: 'has_public_posts',
  number_of_pages: 'number_of_pages',
  canonical: 'canonical',
  primary_focus_keyword: 'primary_focus_keyword',
  primary_focus_keyword_score: 'primary_focus_keyword_score',
  readability_score: 'readability_score',
  is_cornerstone: 'is_cornerstone',
  is_robots_noindex: 'is_robots_noindex',
  is_robots_nofollow: 'is_robots_nofollow',
  is_robots_noarchive: 'is_robots_noarchive',
  is_robots_noimageindex: 'is_robots_noimageindex',
  is_robots_nosnippet: 'is_robots_nosnippet',
  twitter_title: 'twitter_title',
  twitter_image: 'twitter_image',
  twitter_description: 'twitter_description',
  twitter_image_id: 'twitter_image_id',
  twitter_image_source: 'twitter_image_source',
  open_graph_title: 'open_graph_title',
  open_graph_description: 'open_graph_description',
  open_graph_image: 'open_graph_image',
  open_graph_image_id: 'open_graph_image_id',
  open_graph_image_source: 'open_graph_image_source',
  open_graph_image_meta: 'open_graph_image_meta',
  link_count: 'link_count',
  incoming_link_count: 'incoming_link_count',
  prominent_words_version: 'prominent_words_version',
  created_at: 'created_at',
  updated_at: 'updated_at',
  blog_id: 'blog_id',
  language: 'language',
  region: 'region',
  schema_page_type: 'schema_page_type',
  schema_article_type: 'schema_article_type',
  has_ancestors: 'has_ancestors',
  estimated_reading_time_minutes: 'estimated_reading_time_minutes',
  version: 'version',
  object_last_modified: 'object_last_modified',
  object_published_at: 'object_published_at',
  inclusive_language_score: 'inclusive_language_score'
}

exports.Prisma.As_yoast_indexable_hierarchyScalarFieldEnum = {
  indexable_id: 'indexable_id',
  ancestor_id: 'ancestor_id',
  depth: 'depth',
  blog_id: 'blog_id'
}

exports.Prisma.As_yoast_migrationsScalarFieldEnum = {
  id: 'id',
  version: 'version'
}

exports.Prisma.As_yoast_primary_termScalarFieldEnum = {
  id: 'id',
  post_id: 'post_id',
  term_id: 'term_id',
  taxonomy: 'taxonomy',
  created_at: 'created_at',
  updated_at: 'updated_at',
  blog_id: 'blog_id'
}

exports.Prisma.As_yoast_seo_linksScalarFieldEnum = {
  id: 'id',
  url: 'url',
  post_id: 'post_id',
  target_post_id: 'target_post_id',
  type: 'type',
  indexable_id: 'indexable_id',
  target_indexable_id: 'target_indexable_id',
  height: 'height',
  width: 'width',
  size: 'size',
  language: 'language',
  region: 'region'
}

exports.Prisma.As_yoast_seo_metaScalarFieldEnum = {
  object_id: 'object_id',
  internal_link_count: 'internal_link_count',
  incoming_link_count: 'incoming_link_count'
}

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
}

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
}

exports.Prisma.as_actionscheduler_actionsOrderByRelevanceFieldEnum = {
  hook: 'hook',
  status: 'status',
  args: 'args',
  schedule: 'schedule',
  extended_args: 'extended_args'
}

exports.Prisma.as_actionscheduler_groupsOrderByRelevanceFieldEnum = {
  slug: 'slug'
}

exports.Prisma.as_actionscheduler_logsOrderByRelevanceFieldEnum = {
  message: 'message'
}

exports.Prisma.as_awb_critical_cssOrderByRelevanceFieldEnum = {
  css_key: 'css_key',
  mobile_css: 'mobile_css',
  desktop_css: 'desktop_css',
  mobile_preloads: 'mobile_preloads',
  desktop_preloads: 'desktop_preloads',
  updated_at: 'updated_at'
}

exports.Prisma.as_cli_cookie_scanOrderByRelevanceFieldEnum = {
  current_action: 'current_action'
}

exports.Prisma.as_cli_cookie_scan_categoriesOrderByRelevanceFieldEnum = {
  cli_cookie_category_name: 'cli_cookie_category_name',
  cli_cookie_category_description: 'cli_cookie_category_description'
}

exports.Prisma.as_cli_cookie_scan_cookiesOrderByRelevanceFieldEnum = {
  cookie_id: 'cookie_id',
  expiry: 'expiry',
  type: 'type',
  category: 'category',
  description: 'description'
}

exports.Prisma.as_cli_cookie_scan_urlOrderByRelevanceFieldEnum = {
  url: 'url'
}

exports.Prisma.as_cli_scriptsOrderByRelevanceFieldEnum = {
  cliscript_title: 'cliscript_title',
  cliscript_category: 'cliscript_category',
  cliscript_status: 'cliscript_status',
  cliscript_description: 'cliscript_description',
  cliscript_key: 'cliscript_key'
}

exports.Prisma.as_commentmetaOrderByRelevanceFieldEnum = {
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.as_commentsOrderByRelevanceFieldEnum = {
  comment_author: 'comment_author',
  comment_author_email: 'comment_author_email',
  comment_author_url: 'comment_author_url',
  comment_author_IP: 'comment_author_IP',
  comment_content: 'comment_content',
  comment_approved: 'comment_approved',
  comment_agent: 'comment_agent',
  comment_type: 'comment_type'
}

exports.Prisma.as_fusion_form_entriesOrderByRelevanceFieldEnum = {
  value: 'value',
  data: 'data'
}

exports.Prisma.as_fusion_form_fieldsOrderByRelevanceFieldEnum = {
  field_name: 'field_name',
  field_label: 'field_label',
  data: 'data'
}

exports.Prisma.as_fusion_form_submissionsOrderByRelevanceFieldEnum = {
  source_url: 'source_url',
  user_agent: 'user_agent',
  ip: 'ip',
  on_privacy_scrub: 'on_privacy_scrub',
  data: 'data'
}

exports.Prisma.as_fusion_formsOrderByRelevanceFieldEnum = {
  data: 'data'
}

exports.Prisma.as_layersliderOrderByRelevanceFieldEnum = {
  name: 'name',
  slug: 'slug',
  data: 'data'
}

exports.Prisma.as_layerslider_revisionsOrderByRelevanceFieldEnum = {
  data: 'data'
}

exports.Prisma.as_linksOrderByRelevanceFieldEnum = {
  link_url: 'link_url',
  link_name: 'link_name',
  link_image: 'link_image',
  link_target: 'link_target',
  link_description: 'link_description',
  link_visible: 'link_visible',
  link_rel: 'link_rel',
  link_notes: 'link_notes',
  link_rss: 'link_rss'
}

exports.Prisma.as_loginizer_logsOrderByRelevanceFieldEnum = {
  username: 'username',
  ip: 'ip',
  url: 'url'
}

exports.Prisma.as_optionsOrderByRelevanceFieldEnum = {
  option_name: 'option_name',
  option_value: 'option_value',
  autoload: 'autoload'
}

exports.Prisma.as_postmetaOrderByRelevanceFieldEnum = {
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.as_postsOrderByRelevanceFieldEnum = {
  post_content: 'post_content',
  post_title: 'post_title',
  post_excerpt: 'post_excerpt',
  post_status: 'post_status',
  comment_status: 'comment_status',
  ping_status: 'ping_status',
  post_password: 'post_password',
  post_name: 'post_name',
  to_ping: 'to_ping',
  pinged: 'pinged',
  post_content_filtered: 'post_content_filtered',
  guid: 'guid',
  post_type: 'post_type',
  post_mime_type: 'post_mime_type'
}

exports.Prisma.as_term_taxonomyOrderByRelevanceFieldEnum = {
  taxonomy: 'taxonomy',
  description: 'description'
}

exports.Prisma.as_termmetaOrderByRelevanceFieldEnum = {
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.as_termsOrderByRelevanceFieldEnum = {
  name: 'name',
  slug: 'slug'
}

exports.Prisma.as_tm_taskmetaOrderByRelevanceFieldEnum = {
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.as_tm_tasksOrderByRelevanceFieldEnum = {
  type: 'type',
  class_identifier: 'class_identifier',
  description: 'description',
  status: 'status'
}

exports.Prisma.as_usermetaOrderByRelevanceFieldEnum = {
  meta_key: 'meta_key',
  meta_value: 'meta_value'
}

exports.Prisma.as_usersOrderByRelevanceFieldEnum = {
  user_login: 'user_login',
  user_pass: 'user_pass',
  user_nicename: 'user_nicename',
  user_email: 'user_email',
  user_url: 'user_url',
  user_activation_key: 'user_activation_key',
  display_name: 'display_name'
}

exports.Prisma.as_wpo_404_detectorOrderByRelevanceFieldEnum = {
  url: 'url',
  referrer: 'referrer'
}

exports.Prisma.as_yoast_indexableOrderByRelevanceFieldEnum = {
  permalink: 'permalink',
  permalink_hash: 'permalink_hash',
  object_type: 'object_type',
  object_sub_type: 'object_sub_type',
  title: 'title',
  description: 'description',
  breadcrumb_title: 'breadcrumb_title',
  post_status: 'post_status',
  canonical: 'canonical',
  primary_focus_keyword: 'primary_focus_keyword',
  twitter_title: 'twitter_title',
  twitter_image: 'twitter_image',
  twitter_description: 'twitter_description',
  twitter_image_id: 'twitter_image_id',
  twitter_image_source: 'twitter_image_source',
  open_graph_title: 'open_graph_title',
  open_graph_description: 'open_graph_description',
  open_graph_image: 'open_graph_image',
  open_graph_image_id: 'open_graph_image_id',
  open_graph_image_source: 'open_graph_image_source',
  open_graph_image_meta: 'open_graph_image_meta',
  language: 'language',
  region: 'region',
  schema_page_type: 'schema_page_type',
  schema_article_type: 'schema_article_type'
}

exports.Prisma.as_yoast_migrationsOrderByRelevanceFieldEnum = {
  version: 'version'
}

exports.Prisma.as_yoast_primary_termOrderByRelevanceFieldEnum = {
  taxonomy: 'taxonomy'
}

exports.Prisma.as_yoast_seo_linksOrderByRelevanceFieldEnum = {
  url: 'url',
  type: 'type',
  language: 'language',
  region: 'region'
}

exports.Prisma.ModelName = {
  as_actionscheduler_actions: 'as_actionscheduler_actions',
  as_actionscheduler_claims: 'as_actionscheduler_claims',
  as_actionscheduler_groups: 'as_actionscheduler_groups',
  as_actionscheduler_logs: 'as_actionscheduler_logs',
  as_awb_critical_css: 'as_awb_critical_css',
  as_cli_cookie_scan: 'as_cli_cookie_scan',
  as_cli_cookie_scan_categories: 'as_cli_cookie_scan_categories',
  as_cli_cookie_scan_cookies: 'as_cli_cookie_scan_cookies',
  as_cli_cookie_scan_url: 'as_cli_cookie_scan_url',
  as_cli_scripts: 'as_cli_scripts',
  as_commentmeta: 'as_commentmeta',
  as_comments: 'as_comments',
  as_fusion_form_entries: 'as_fusion_form_entries',
  as_fusion_form_fields: 'as_fusion_form_fields',
  as_fusion_form_submissions: 'as_fusion_form_submissions',
  as_fusion_forms: 'as_fusion_forms',
  as_layerslider: 'as_layerslider',
  as_layerslider_revisions: 'as_layerslider_revisions',
  as_links: 'as_links',
  as_loginizer_logs: 'as_loginizer_logs',
  as_options: 'as_options',
  as_postmeta: 'as_postmeta',
  as_posts: 'as_posts',
  as_term_relationships: 'as_term_relationships',
  as_term_taxonomy: 'as_term_taxonomy',
  as_termmeta: 'as_termmeta',
  as_terms: 'as_terms',
  as_tm_taskmeta: 'as_tm_taskmeta',
  as_tm_tasks: 'as_tm_tasks',
  as_usermeta: 'as_usermeta',
  as_users: 'as_users',
  as_wpo_404_detector: 'as_wpo_404_detector',
  as_yoast_indexable: 'as_yoast_indexable',
  as_yoast_indexable_hierarchy: 'as_yoast_indexable_hierarchy',
  as_yoast_migrations: 'as_yoast_migrations',
  as_yoast_primary_term: 'as_yoast_primary_term',
  as_yoast_seo_links: 'as_yoast_seo_links',
  as_yoast_seo_meta: 'as_yoast_seo_meta'
}

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`
        } else {
          message =
            'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' +
            runtime.prettyName +
            '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
