/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */

Object.defineProperty(exports, '__esModule', { value: true })

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')

const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.17.1
 * Query Engine version: 272a37d34178c2894197e17273bf937f25acdeac
 */
Prisma.prismaVersion = {
  client: '6.17.1',
  engine: '272a37d34178c2894197e17273bf937f25acdeac'
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.validator = Public.validator

/**
 * Extensions
 */
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`)
}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}

/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
})

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  login: 'login',
  email: 'email',
  password: 'password',
  displayName: 'displayName',
  role: 'role',
  isActive: 'isActive',
  registeredAt: 'registeredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.UserMetaScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  key: 'key',
  value: 'value'
}

exports.Prisma.PageScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  status: 'status',
  authorId: 'authorId',
  parentId: 'parentId',
  menuOrder: 'menuOrder',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.PageTranslationScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  lang: 'lang',
  title: 'title',
  content: 'content',
  excerpt: 'excerpt'
}

exports.Prisma.PageMetaScalarFieldEnum = {
  id: 'id',
  pageId: 'pageId',
  key: 'key',
  value: 'value'
}

exports.Prisma.ArticleScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  status: 'status',
  authorId: 'authorId',
  parentId: 'parentId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.ArticleTranslationScalarFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  lang: 'lang',
  title: 'title',
  content: 'content',
  excerpt: 'excerpt'
}

exports.Prisma.ArticleMetaScalarFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  key: 'key',
  value: 'value'
}

exports.Prisma.PortfolioScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  status: 'status',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.PortfolioTranslationScalarFieldEnum = {
  id: 'id',
  portfolioId: 'portfolioId',
  lang: 'lang',
  title: 'title',
  content: 'content',
  excerpt: 'excerpt'
}

exports.Prisma.PortfolioMetaScalarFieldEnum = {
  id: 'id',
  portfolioId: 'portfolioId',
  key: 'key',
  value: 'value'
}

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  price: 'price',
  currency: 'currency',
  stock: 'stock',
  vendorId: 'vendorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.ProductTranslationScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  lang: 'lang',
  title: 'title',
  description: 'description'
}

exports.Prisma.ProductMetaScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  key: 'key',
  value: 'value'
}

exports.Prisma.CommentScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  pageId: 'pageId',
  articleId: 'articleId',
  portfolioId: 'portfolioId',
  productId: 'productId',
  content: 'content',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.CommentMetaScalarFieldEnum = {
  id: 'id',
  commentId: 'commentId',
  key: 'key',
  value: 'value'
}

exports.Prisma.TermScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  group: 'group'
}

exports.Prisma.TermTaxonomyScalarFieldEnum = {
  id: 'id',
  termId: 'termId',
  taxonomy: 'taxonomy',
  description: 'description',
  parentId: 'parentId',
  count: 'count'
}

exports.Prisma.TermRelationshipScalarFieldEnum = {
  id: 'id',
  articleId: 'articleId',
  pageId: 'pageId',
  portfolioId: 'portfolioId',
  productId: 'productId',
  termTaxonomyId: 'termTaxonomyId'
}

exports.Prisma.MenuScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  name: 'name',
  items: 'items',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
}

exports.Prisma.SettingScalarFieldEnum = {
  key: 'key',
  value: 'value'
}

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
}

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
}

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
}

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
}

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
}
exports.Role = exports.$Enums.Role = {
  GUEST: 'GUEST',
  SUBSCRIBER: 'SUBSCRIBER',
  CONTRIBUTOR: 'CONTRIBUTOR',
  AUTHOR: 'AUTHOR',
  EDITOR: 'EDITOR',
  ADMIN: 'ADMIN',
  SUPERADMIN: 'SUPERADMIN'
}

exports.Status = exports.$Enums.Status = {
  DRAFT: 'DRAFT',
  PENDING: 'PENDING',
  PUBLISHED: 'PUBLISHED',
  ARCHIVED: 'ARCHIVED',
  TRASH: 'TRASH'
}

exports.Prisma.ModelName = {
  User: 'User',
  UserMeta: 'UserMeta',
  Page: 'Page',
  PageTranslation: 'PageTranslation',
  PageMeta: 'PageMeta',
  Article: 'Article',
  ArticleTranslation: 'ArticleTranslation',
  ArticleMeta: 'ArticleMeta',
  Portfolio: 'Portfolio',
  PortfolioTranslation: 'PortfolioTranslation',
  PortfolioMeta: 'PortfolioMeta',
  Product: 'Product',
  ProductTranslation: 'ProductTranslation',
  ProductMeta: 'ProductMeta',
  Comment: 'Comment',
  CommentMeta: 'CommentMeta',
  Term: 'Term',
  TermTaxonomy: 'TermTaxonomy',
  TermRelationship: 'TermRelationship',
  Menu: 'Menu',
  Setting: 'Setting'
}

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`
        } else {
          message =
            'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' +
            runtime.prettyName +
            '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
